version: "3"
services:
  web:
    build: .
    restart: unless-stopped
    volumes:
        - ./:/app
    ports:
      - "3000:3000"
    env_file:
      - ./.env.dev
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db

  mongo-express:
    image: mongo-express
    depends_on: [mongo]
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  rabbitmq:
    image: 'rabbitmq:3.8-management-alpine'
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - './rabbitmq_data:/var/lib/rabbitmq/mnesia'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
